# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
