# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='new_name',
        ),
        migrations.AddField(
            model_name='image',
            name='old_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
