# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160515_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 15, 8, 44, 20, 886721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.PositiveIntegerField(),
        ),
    ]
