# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160515_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 15, 15, 45, 57, 76357, tzinfo=utc)),
        ),
    ]
